typography_spectrum: 0.48179475707001984
content_rating:
  adult: true
color:
  brandStrength: 0.9489394288975745
  lightness: 0.3477667903061956
  saturation: 0.4290693362709135
  rhythmicContrast: 0.08155544498004019
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
layout_spectrum: 0.611017576418817
author:
  name: Jonathan Roby
  email: jonitron@hotmail.com
name: Jonitron
navigation:
  - name: A place to find me.
    url: 'http://jonitron.myportfolio.com/'
    type: external
  - name: 'Another '
    url: 'https://500px.com/jonitron'
    type: external
title: Jonitron
description: 'Photographs [among other things]'
